sudo: required
service:
  -docker

before_install:
  - docker build -t kazikhalil/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true  kazikhalil/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "Docker"
  env: "Docker-env"
  bucket-name: "elasticbeanstalk-eu-central-1-234924328954"
  bucket_path: "Docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
